name: CI

on:
  pull_request

jobs:
  build-and-test:
    name: Test Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 14.1.0
        
    - name: Build
      run: |
        set -o pipefail
        xcodebuild build \
        -scheme iOSGitHubActions \
        -destination 'platform=iOS Simulator,name=iPhone 8' \
        
    - name: Test
      run: |
        set -o pipefail
        xcodebuild test \
        -scheme iOSGitHubActions \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
